name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install software
      run: sudo apt-get install -y libopengl-dev libglfw3-dev
    - name: make
      run: pwd && make
